export const motivationalPhrases = [
  'Siga em frente',
  'Força!',
  'Você pode',
  'Tente de novo',
  'Persista',
  'Coragem!',
  'Continue',
  'Não pare',
  'Inspire-se',
  'Avance',
  'Renove-se',
  'Vá além',
  'Sonhe alto',
  'Atreva-se',
  'Eleve-se',
  'Brilhe',
  'Lute',
  'Supere',
  'Cresça',
  'Voe alto',
  'Conquiste',
  'Acredite',
  'Realize',
  'Motive-se',
  'Inove',
  'Transforme',
  'Desafie-se',
  'Avance',
  'Empodere',
  'Ascenda',
  'Ouse mais',
  'Vá firme',
  'Mantenha-se',
  'Persistente',
  'Resiliente',
  'Foco total',
  'Sem medo',
  'Passe adiante',
  'Erga-se',
  'Reflita',
  'Aja agora',
  'Siga a luz',
  'Vibrações',
  'Energize-se',
  'Renasça',
  'Evolua',
  'Abra caminhos',
  'Mire alto',
  'Fixe metas',
  'Ultrapasse',
];
