name: E2E Tests with Maestro on iOS Simulator

on:
  push:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v2

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
            xcode-version: '15.2.0'

      # Setup do Node.js e instalação de dependências do projeto
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.12.1'

      - name: List available simulators
        run: xcrun simctl list devices
        
      - name: Install npm dependencies
        run: npm install --legacy-peer-deps

      # Setup do Expo CLI
      - name: Install Expo CLI
        run: npm install -g expo-cli

      # Executar expo prebuild para preparar o projeto nativo
      - name: Run expo prebuild
        run: npx expo prebuild --platform ios

      - name: Modify Podfile for modular headers
        run: |
          echo "use_modular_headers!" >> ios/Podfile

      # Instalação do CocoaPods com o Podfile modificado
      - name: Install Pods
        run: |
         cd ios
         pod install    

      # Instalação do Maestro
      - name: Install Maestro
        run: curl -Ls "https://get.maestro.mobile.dev" | bash
     
      - name: Clean CocoaPods Cache
        run: pod cache clean --all

      - name: Clean Xcode build
        run: xcodebuild -workspace ios/T.xcworkspace -scheme T clean

      # Compilação do app para o simulador iOS utilizando Xcode
      - name: Build iOS App
        run: |
          xcodebuild -workspace ios/T.xcworkspace -scheme T -configuration Debug -sdk iphonesimulator -derivedDataPath ./build

      # Iniciar o simulador iOS
      - name: Start iOS Simulator
        run: |
          xcrun simctl boot F73A6F20-C53B-4B22-B423-453E243D2D1E
          sleep 30

      # Instalar o app no simulador
      - name: Install App on Simulator
        run: |
          app_path="./build/Build/Products/Debug-iphonesimulator/T.app"
          xcrun simctl install booted "$app_path"

      # Iniciar o app no simulador
      - name: Launch App on Simulator
        run: |
          bundle_id="com.jv.t"
          xcrun simctl launch booted "$bundle_id"

      # Executar os testes de UI com o Maestro
      - name: Run Maestro Studio
        run: maestro test test.yaml
